# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "file",source: "./deployment.yaml",destination: "/tmp/deployment.yaml"
  config.vm.provision "shell", path: "script.sh"
  config.vm.define "kubernetes" do |vm1|
  vm1.vm.hostname ="kubernetes"
  vm1.vm.box = "ubuntu/xenial64"
  vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.provider "virtualbox" do |vb|
    vb.name="kubernetes"
    vb.gui = false
    vb.memory = "3024"
  end
end
end