apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-container1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic-container1
    spec:
      containers:
      - name: petclinic-container1
        image: krishnaguru/docker-spring-boot:firsttry
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-container2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic-container2
    spec:
      containers:
      - name: petclinic-container2
        image: krishnaguru/docker-spring-boot:firsttry
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-container1-svc
  labels:
    app: petclinic-container1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: petclinic-container1
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-container2-svc
  labels:
    app: petclinic-container2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30081
  selector:
    app: petclinic-container2