# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu-vm2" do |vm2|
  vm2.vm.hostname ="ubuntu-vm2"
  vm2.vm.box = "ubuntu/xenial64"
  vm2.vm.provision "file",source: "./Configurationfiles/sshd_config",destination: "/tmp/sshd_config"
  vm2.vm.provision "shell", path: "./Scripts/script-vm2.sh"
  vm2.vm.network "private_network", ip: "192.168.33.20"
  vm2.vm.provider "virtualbox" do |vb|
    vb.name="ubuntu-vm2"
    vb.gui = false
    vb.memory = "1024"

    end
  end


 
  config.vm.define "ubuntu-vm" do |vm1|
  vm1.vm.hostname ="ubuntu-vm"
  vm1.vm.box = "ubuntu/xenial64"
  vm1.vm.provision "file",source: "./Configurationfiles/ssh_config",destination: "/tmp/ssh_config"
  vm1.vm.provision "shell", path: "./Scripts/script-vm1.sh"
  vm1.vm.network "private_network", ip: "192.168.33.10"
      vm1.vm.provider "virtualbox" do |vb|
      vb.name="ubuntu-vm"
      vb.gui = false
      vb.memory = "1024"
    end
  end
end
